### ISSUE TITLE
Documentation on how to use rddl2plmnt minting on testnet and mainnet.

### ISSUE THREAD

**Issue by eckelj** [rddl-network/docs#4]
- [ ] Step by Step guide on how to convert RDDL to Planetmint
- [x] Short description on how the mechanism works
- [ ] What are the prerequisite's by confirmation from Liquid
- [x] Target address and curl request

**Comment by LaurentMontBlanc** [comment]
https://app.gitbook.com/o/uqUhSEGIfC8qHSl7XLQe/s/3ylQ6zh9lLdOSSmCZHg4/~/changes/75/tutorials/wip-converting-rddl-to-plmnt

documented here WIP
